[package]
name = "filty"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.14"

[lib]
name = "filty"
path = "src/lib.rs"

[[bin]]
name = "filty_test"
path = "src/bin/bin.rs"